services:
  backend:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - LOG_LEVEL=INFO

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend 