version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: ./src/Dockerfile.dev
    container_name: ai_backend_dev
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    networks:
      - app_network_dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:5000
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network_dev

networks:
  app_network_dev:
    name: ai_network_dev
    driver: bridge 