services:
  backend:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src:delegated
      - ./.env:/app/.env:ro
      - ./hot_reload.sh:/app/hot_reload.sh:ro
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    name: ai_network
    driver: bridge 